### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by utkarsh006**
- See the changes [HERE](https://github.com/utkarsh006/RoomDatabase-Youtube/tree/Readme_Update)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@ezatpanah Kindly Review

**Comment by ezatpanah** [comment]
I have suggection , if you are agree :
https://github.com/ezatpanah/Flow-Database-Youtube
there is the new version of RoomDatabase repo with latest library and method, if you think it matches with your scope of Improvements ,that would be nice to link it newer version of repo ,
what do you think?

**Comment by utkarsh006** [comment]
@ezatpanah Yes we can link it to that repo. But we should make this repo updated with the latest changes. Moreover, a beginner should know how many topics are still left to learn to make this project work good.

**Comment by utkarsh006** [comment]
@ezatpanah I have linked that repo to this repo now. Kindly Review the PR.

**Review by ezatpanah — COMMENTED** [review]
done

**Comment by ezatpanah** [comment]
cool, Thanks, I like your hand note , that was cool 🤩

**Comment by utkarsh006** [comment]
> cool, Thanks, I like your hand note , that was cool 🤩

@ezatpanah Thanks a ton 😎 Loved working with you !

**Pull request merged**
